// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.bgfurfeature.hello.rpc;

public final class Hello {
  private Hello() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bgfurfeature_hello_rpc_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bgfurfeature_hello_rpc_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bgfurfeature_hello_rpc_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bgfurfeature_hello_rpc_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013hello.proto\022\032com.bgfurfeature.hello.rp" +
      "c\"\034\n\014HelloRequest\022\014\n\004name\030\001 \001(\t\"\035\n\nHello" +
      "Reply\022\017\n\007message\030\001 \001(\t2\316\001\n\007Greeter\022^\n\010Sa" +
      "yHello\022(.com.bgfurfeature.hello.rpc.Hell" +
      "oRequest\032&.com.bgfurfeature.hello.rpc.He" +
      "lloReply\"\000\022c\n\rSayHelloAgain\022(.com.bgfurf" +
      "eature.hello.rpc.HelloRequest\032&.com.bgfu" +
      "rfeature.hello.rpc.HelloReply\"\000B\002P\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_bgfurfeature_hello_rpc_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bgfurfeature_hello_rpc_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bgfurfeature_hello_rpc_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_bgfurfeature_hello_rpc_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_bgfurfeature_hello_rpc_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bgfurfeature_hello_rpc_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
